spring:
  application:
    name: hello
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/imooc?characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    username: root
    password: root

  # 关闭集群session配置
  session:
    store-type: none
  # redis缓存
  redis:
    host: 49.235.110.134
    database: 0
    port: 6379
    password: lovingliu
    timeout: 3000ms
    jedis:
      pool:
        max-active: 10
        max-wait: -1ms
        max-idle: 10
        min-idle: 0
server:
  port: 8001
